### PR TITLE
Add rise to the set of text state operator helpers

### PR DESCRIPTION
**Pull request by petergoldstein**
This PR adds helpers for the rise and leading text state operators to the pdf-core.

It also does a little reorganization based on feedback from the last PR.

### CODE REVIEW

**Review by gettalong — CHANGES_REQUESTED** [review]
I think adding "leading" does not make any sense due to the way this PDF operator works. If one sets this value, one later has to use one of the operators `T*` or `'` (see section 9.4 of PDF 1.7 spec). However, Prawn only uses the positioning operators `Tm` or `Td` together with the text showing operators `TJ` and `Tj` (see https://github.com/prawnpdf/pdf-core/blob/master/lib/pdf/core/text.rb#L255-L284).

So even if this was set, it is not used anywhere and won't make a difference in the output. Therefore I recommend removing the implementation for leading for now.

**Comment by petergoldstein** [comment]
@gettalong I think that's a fair point, assuming that pdf-core is meant to be used exclusively by `prawn`.

That leads to a more general question I have about `pdf-core` / `prawn`.  Specifically, why was `pdf-core` split out?  If it's just supposed to be used by `prawn`, then it leads to some very inconvenient divisions (see PDF/A-1b, Encrypt) that make the code more indirect and more difficult to manage.  It seems like it would be easier to update and maintain if it were a single codebase.

If it's supposed to be a generic library usable by other frameworks than `prawn` then it seems like it should strive for a full feature set.

@gettalong or @pointlessone do you have any insight on the above you can share?

**Comment by gettalong** [comment]
@petergoldstein As far as I know Prawn is the only library using pdf-core since they are tightly coupled. I *think* Prawn depends on pdf-core but that pdf-core also depends on Prawn for some things (was way back when I looked closer at the two libraries but may have changed in the meantime).

pdf-core was split out to make it possible, as you assumed, to build something else on top of it. However, the split was not completely done and is in the current state every since. It didn't really matter for Prawn since it just kept on working. Something similar happened with prawn-template (which is why there are (or at least were) still some methods in pdf-core/prawn that depend on prawn-template).

For a fully-featured library to build PDF applications on top pdf-core would need a lot more. Given that the focus is on Prawn I would recommend integrating pdf-core back into prawn to, as you say, make things simpler again.

**Comment by pointlessone** [comment]
As @gettalong mentioned, pdf-core was extracted from Prawn. The idea, indeed, was to make it concerned with all things low-level PDF (e.g. file structure, primitive drawing operations, etc.) while keeping higher level stuff in Prawn (e.g. text layout, boxes, columns, etc.). prawn-template was also extracted from Prawn. Neither was fully complete.

In principle, I agree with the decoupling decision. PDF (as a format) and layout are two very distinct concerns. I'd love this separation complete. Maybe we can work towards Prawn 3 where it's actually accomplished. We might break the API a little, too, if we need for it to get done.

That said, is someone makes an assessment and it turns out there's just too much work for it ever be done we probably should accept that and merge pdf-core back in.

**Comment by petergoldstein** [comment]
@pointlessone Thanks for the clarification.  Maybe we can discuss approach in the near future after a few of the currently outstanding issues are resolved.

@gettalong can you please review as I've removed leading?  Thanks..

**Review by pointlessone — APPROVED** [review]

**Comment by pointlessone** [comment]
@petergoldstein Thank you.

**Pull request merged**
